// apps/ng-app/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import '@web-comp-app/shared/ui-components';

@Component({
  selector: 'web-comp-app-root',
  template: `
    <h1>Angular App</h1>
    <div style="border: 2px solid green;">
      <wc-search-bar #searchBarId [attr.namelist]="nameList"></wc-search-bar>
    </div>
    <div *ngFor="let item of items">
      <div>{{ item }}</div>
    </div>
  `,
})
export class AppComponent implements AfterViewInit {
  nameList = [
    'Sandy',
    'Alfred',
    'Maximilian',
    'Tadeus',
    'Spongebob',
    'James',
    'Lisa',
    'Sam',
    'Jack',
    'Simon',
    'Dr No',
    'Sebastian',
    'Franz',
    'Eva',
    'Manuel',
    'Karl',
  ];

  @ViewChild('searchBarId') mySearchBar!: ElementRef;

  items: string[] = [];

  ngAfterViewInit() {
    this.mySearchBar.nativeElement.addEventListener(
      'onBlurEvent',
      (evt: any) => {
        console.log(evt);
        this.items.push(evt.detail);
      }
    );
  }
}

// apps/react-app/src/app/app.tsx
import '@web-comp-app/shared/ui-components';

import { useState } from 'react';

export function App() {
  const [count, setCount] = useState(0);

  const nameList = [
    'Sandy',
    'Alfred',
    'Maximilian',
    'Tadeus',
    'Spongebob',
    'James',
    'Lisa',
    'Sam',
    'Jack',
    'Simon',
    'Dr No',
    'Sebastian',
    'Franz',
    'Eva',
    'Manuel',
    'Karl',
  ];

  setTimeout(() => {
    console.log("wc-search-bar::: ", document.getElementsByTagName('wc-search-bar'));
  },1000);

  return (
    <div>
      <h1>React App</h1>
      <wc-search-bar   namelist={nameList}></wc-search-bar>
    </div>
  );


  
  
}

export default App;


// <wc-search-bar #searchBarId [attr.namelist]="nameList"></wc-search-bar>
